<?php  if ( ! defined('BASEPATH')) exit('No direct script access allowed');

class Sitemap_model extends CI_Model
{

    function generate($table)
    {
        $this->db->select('judul_seo,hari,tanggal,jam');
        $this->db->from($table);
        $this->db->order_by('id_berita',"DESC");
        $query = $this->db->get();
        return $query->result();
    }
    function generate_kategori($table)
    {
        $this->db->select('kategori_seo');
        $this->db->from($table);
        $this->db->order_by('id_kategori',"DESC");
        $query = $this->db->get();
        return $query->result();
    }
    public function view_join_one_limit($table1,$table2,$field,$order,$ordering,$baris,$dari){
          $this->db->select('*');
          $this->db->from($table1);
          $this->db->join($table2, $table1.'.'.$field.'='.$table2.'.'.$field);
          $this->db->order_by($order,$ordering);
          $this->db->limit($dari, $baris);
          return $this->db->get()->result();
      }
      public function view_join_one($table1,$table2,$field,$where,$order,$ordering,$baris,$dari){
          $this->db->select('*');
          $this->db->from($table1);
          $this->db->join($table2, $table1.'.'.$field.'='.$table2.'.'.$field);
          $this->db->where($where);
          $this->db->order_by($order,$ordering);
          $this->db->limit($dari, $baris);
          return $this->db->get();
      }

}

/* End of file Berita_model.php */
/* Location: ./application/models/Berita_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2016-10-17 02:19:21 */
/* http://harviacode.com */
